version: "3.9"
services:
  frontend:
    build: ./docker/frontend
    ports:
      - "5173:5173"
    env_file: ./frontend/.env
    depends_on:
      - backend

  backend:
    build: ./docker/backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:
